### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by raonyguimaraes** [basespace/basespace-python-sdk#19]
Hi, 

Today I managed to get this sdk working with python3 with some small changes.

https://github.com/raonyguimaraes/basespace-python3-sdk

Is there anyone already working on this ?

Should I submit it as a pull request or to a new (specific) branch ?

Kind Regards.

**Comment by psaffrey-illumina** [comment]
Wow, great! By all means submit a PR :)

Quite a few changes have been made to the SDK to support BaseSpaceCLI - these are in the develop branch. It might be worth seeing whether your changes can be merged there without modifications.

**Comment by raonyguimaraes** [comment]
Thank you, just submitted! 
Cheers.
